      "echo '***Remove lock***'",
      "sudo rm /var/lib/apt/lists/lock",
      "echo '***Remove lock from cache***'",
      "sudo rm /var/cache/apt/archives/lock",
      "echo '***Add the GPG key for the official Docker repository to your system***'",
      "curl -fs SL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -",
      "echo '***Add the Docker repository to APT sources'***",
      "sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'",
      "echo '***Update the package database with the Docker packages from the newly added repo***'",
      "sleep 10",
      "sudo apt-get update",
      "echo '***Make sure you are about to install from the Docker repo instead of the default Ubuntu 16.04 repo***'",
      "sleep 10",
      "apt-cache policy docker-ce",
      "echo '***Install Docker***'",
      "sleep 10",
      "sudo apt-get install -y docker-ce",
      "echo '***Check that docker is running***'",
      "sudo systemctl status docker",
      "echo '***add the current username to the docker group***'",
      "sudo usermod -aG docker ubuntu"